### ISSUE TITLE
UI src part

### ISSUE THREAD

**Issue by avavdoshin** [synopse/mORMot2#34]
Can you please provide UI part for mormot2?
mormot offered grid to display content in mormotui unit and orm-driven office toolbar in mormottoobar unit, but mormot2 missed such units. Mormotreport unit will be nice too.
I understand that mormot2 is currently WIP, but unfortunately original mormot 1.18 doesn't work at all with current CodeTyphon version from pilotlogic which I use for a long time.

**Comment by mdbs99** [comment]
I believe that soon we will have a grid that works natively with JSON.

**Comment by LongDirtyAnimAlf** [comment]
Two questions:
You could use FPC + Lazarus as a replacement for CodeTyphon.
What error do you get with CodeTyphon.

**Comment by avavdoshin** [comment]
> You could use FPC + Lazarus as a replacement for CodeTyphon.
Yes, of course. mormot1.18 works very well with FPC 3.2.0 and Lazarus 2.1.0 compiled via FPCUPDeluxe. But CodeTyphon is my main worktool and mormot2 work well with CodeTyphon (FreePascal 3.3.1 Rev :2107010503, Typhon V-IDE 7.5 Rev :2107010503).
I just discovered mORMot and wonder how simple can be ORM. I'm just study mormot and all it's features, so why not study latest version? Ability to have grid of objects, toolbar and some kind of reporting tool in a few lines of code will be very helpful for me.

I suppose that this error because of FPC version used in CodeTyphon.

> What error do you get with CodeTyphon.
I will install mormot1.18 again later to reproduce this error and wrote **what exactly** shows my debugger.
There is no error message at all if just run application (without debugging). It doesn't show main form, it terminates immediately after start.
When run with debugging there is GPF without HASDIRECTTYPEINFO option in line 51225 SynCommons.pas and with HASDIRECTTYPEINFO option in line 51228.

Sorry for my lame english, i try my best

**Comment by LongDirtyAnimAlf** [comment]
In synopse.inc:
{$if not defined(VER3_0) and not defined(VER3_2) and not defined(VER2)}
    {$define FPC_PROVIDE_ATTR_TABLE} // to be defined since SVN 42356-42411 <------------------------------------------
    // on compilation error in SynFPCTypInfo, undefine the above conditional
    // see https://lists.freepascal.org/pipermail/fpc-announce/2019-July/000612.html
{$ifend}

**Comment by avavdoshin** [comment]
Ooops...
I missed this part of installation instruction, what a shame for me.
Thank you very much, now it's work perfectly in CodeTyphon!
