### ISSUE TITLE
Cannot Compile in Delphi 13.0

### ISSUE THREAD

**Issue by myonlylonely** [synopse/mORMot2#380]
```pascal
function TDocVariantData.GetValuesByStartName(const aStartName: RawUtf8;
  TrimLeftStartName: boolean): variant;
//...
    TDocVariant.NewFast(result);
//...
```
Cannot Compile in Delphi 13.0, this line has F2084 Internel Error C2802.

**Comment by synopse** [comment]
What if we change:
````
PVarData(@aValue)^ := DV_FAST[aKind];
```

**Comment by myonlylonely** [comment]
No, it does not help.
I have reported this to emb, and they have comfirmed it is a bug, but they didn't say when they will fix this.

**Comment by LukaszDemczuk** [comment]
Bug is for 32bit compilation, 64bit works fine.

**Comment by synopse** [comment]
I tried to circumvent the issue.
Should not change much in terms of performances.

**Comment by myonlylonely** [comment]
It is now working.
I think we should keep this issue open. Emb might fix this in a hot fix, and we could revert this workaround when emb fixes this.

**Comment by myonlylonely** [comment]
Marco replied that they expect this fixed in the next update.

**Comment by synopse** [comment]
If only...
